[package]
name = "linch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex="1"
egui="0.22"
clap="4"
lexical-sort="0.3"
